---
apiVersion: v1
kind: Namespace
metadata:
  name: testapp
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: testapp
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./app1
  prune: true
  retryInterval: 1m0s
  sourceRef:
    kind: GitRepository
    name: testrepo
  targetNamespace: testapp
  timeout: 3m0s
  wait: true
