---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: testrepo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://github.com/Nadyita/testproject.git
  secretRef:
    name: github-auth
