---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: testapp
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: testapp
  filterTags:
    pattern: '^latest-(?P<timestamp>.*)$'
    extract: '$timestamp'

  policy:
    alphabetical:
      order: asc
